# Generated by Django 4.0.1 on 2023-01-28 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=25, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='idProducto')),
                ('nombreProducto', models.CharField(max_length=25, verbose_name='nombreProducto')),
                ('precio', models.CharField(blank=True, max_length=6, null=True, verbose_name='Precio')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('nombreCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='nombreVategoria')),
            ],
        ),
    ]
