# Generated by Django 3.2.8 on 2023-01-29 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/core/img/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='nombreCategoria'),
        ),
    ]
